### ISSUE TITLE
subprocess.CalledProcessError: when executing memcdump

### ISSUE THREAD

**Issue by billmetangmo** [juanber84/memcached-dump#2]
=================  Expected behaviour ==============
Data saved inside the memcahed

================= What I got ================
conecting...
checking keys...
Traceback (most recent call last):
  File "memcacheddump.py", line 23, in <module>
    output = subprocess.check_output("memcdump --servers="+host, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'memcdump --servers=127.0.0.1' returned non-zero exit status 1

================== Environment =============

=== Operating System ===
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

===  Python =====
Python 2.7.15rc1

**Comment by licaon-kter** [comment]
Line 24 memcacheddump.py modify it as `output = subprocess.check_output("memcdump --servers="+hostport+"|| true", shell=True)` as for some reason `memcdump` outputs exit code 1 while outputting the actual data too.

Since you'll silence any memcdump errors you'll want to check that the daemon is at least actually running so 
```
$([ `pgrep -n memcached` ] && return 0 || return 1) && python memcacheddump.py -f memdump
```
is helpful.
